### ISSUE TITLE
请教引用和at这些文本消息如何构建呢？

### ISSUE THREAD

**Issue by gclm** [Nyayurn/YurnQbotFramework#1]
目前我使用QuoteElement构造出现的引用文本不生效

**Comment by Nyayurn** [comment]
Chronocat并不支持发送和接收引用消息, AtElement有静态方法atUser(String id)和atType(String type)

**Comment by gclm** [comment]
hi，请问你这边获取用户列表的接口正常吗？我这边出现404

**Comment by Nyayurn** [comment]
我这也是404, 那就是cc还没实现这个API了
